"use client";

import type { DemoSnapshot } from "../lib/automatic-demo";
import { buildDailySummary, type CurrencyTotal } from "../lib/daily-summary";

function Amounts({ rows }: { rows: CurrencyTotal[] }) {
  return rows.length ? <ul className="bullet-list">{rows.map(row => <li key={row.currency}>{row.currency} {row.amount} · {row.count} open item{row.count === 1 ? "" : "s"}</li>)}</ul> : <p>No open items due in this period in the supplied records.</p>;
}

export default function DailyMoneySummary({ snapshot, onNavigate }: { snapshot: DemoSnapshot | null; onNavigate: (screen: "automatic" | "planning") => void }) {
  const summary = buildDailySummary(snapshot);
  if (!summary.available) return <article className="panel"><h2>Your daily money summary</h2><p>{summary.reason}</p><button className="button secondary" onClick={() => onNavigate("automatic")}>Review the example data</button></article>;
  return <section aria-label="Daily money summary">
    <article className="panel"><h2>Your daily money summary</h2><p><strong>Fictional example · {summary.company}</strong></p><p>Based on the supplied snapshot dated {summary.asOf}, update {summary.cycle}. This is not today’s bank position. Due dates below cover {summary.asOf} through {summary.end}.</p><p className="muted">Cash means money in accounts after restrictions and existing commitments. It excludes unused bank credit. Expected customer payments are not money already received.</p>{!summary.marketHealthy && <p role="status">The currency-price refresh failed. USD cash values use the last checked fictional prices; review them before relying on the summary.</p>}</article>
    <div className="two-col"><article className="panel"><h3>Money available now</h3><p><strong>USD {summary.cash}</strong></p><p>Minimum to keep: USD {summary.minimum}.</p><p>{summary.gap === "0.00" ? "The supplied cash balance meets this minimum." : `Gap below your minimum: USD ${summary.gap}. Review upcoming payments and the cash plan.`}</p></article><article className="panel"><h3>Company locations needing review</h3>{summary.entitiesNeedingReview.length ? <ul className="bullet-list">{summary.entitiesNeedingReview.map(name => <li key={name}>{name}</li>)}</ul> : <p>No location is below its cash minimum or forecast minimum in this snapshot.</p>}<p className="muted">A group total does not mean cash can freely move between countries.</p></article></div>
    <div className="two-col"><article className="panel"><h3>Money expected in the next 7 days</h3><Amounts rows={summary.incoming} /><p className="muted">Scheduled amounts, not guaranteed receipts. Different currencies are shown separately.</p></article><article className="panel"><h3>Money due out in the next 7 days</h3><Amounts rows={summary.outgoing} /><p className="muted">Open scheduled payments. Check the original records before approving a payment.</p></article></div>
    <article className="panel"><h3>Open items past their due date</h3>{summary.overdue.length ? <div className="table-scroll"><table><caption>Overdue items from the supplied fictional feed; these are excluded from the upcoming totals.</caption><thead><tr><th>Reference</th><th>Company</th><th>Due date</th><th>Expected direction</th><th>Amount</th></tr></thead><tbody>{summary.overdue.map(flow => <tr key={flow.id}><td>{flow.id}</td><td>{flow.entity}</td><td>{flow.date}</td><td>{flow.direction === "INFLOW" ? "Money in" : "Money out"}</td><td>{flow.currency} {flow.amount}</td></tr>)}</tbody></table></div> : <p>No overdue open items in the supplied records. Missing records could change this result.</p>}<p className="muted">An open overdue item is a review signal, not proof that a customer failed to pay. Check matching bank and accounting records.</p><button className="button secondary" onClick={() => onNavigate("automatic")}>Review source updates</button>{" "}<button className="button secondary" onClick={() => onNavigate("planning")}>Try a cash plan</button></article>
  </section>;
}
