"use client";
import { useMemo, useState } from "react";
import { Assumptions, Flow, Mapping, parseCsv, simulate, validateRows, suggestMapping } from "../lib/planning";

const keys = ["id", "date", "amount", "direction", "currency", "entity", "category", "probability"] as const;
const titles = { id: "Reference *", date: "Due date *", amount: "Amount *", direction: "Inflow / outflow", currency: "Currency", entity: "Entity", category: "Cash-flow category", probability: "Receipt probability" };
const csvTemplate = "id,date,amount,direction,currency,entity,category,probability\nCARGO-01,2026-10-07,18000000,OUTFLOW,USD,Demo UK,CRUDE_PURCHASE,1\nSALE-01,2026-10-10,22000000,INFLOW,USD,Demo UK,PRODUCT_SALE,1\nFREIGHT-01,2026-10-08,1500000,OUTFLOW,USD,Demo UK,FREIGHT,1\nUK-OPS,2026-10-12,1200000,OUTFLOW,GBP,Demo UK,OPERATING,1\nSG-OPS,2026-10-12,2000000,OUTFLOW,SGD,Demo Singapore,OPERATING,1\n";
const defaultMapping = Object.fromEntries(keys.map(k => [k, k])) as Mapping;
const sampleFlows = validateRows(parseCsv(csvTemplate).rows, defaultMapping).flows;
const defaults: Assumptions = { start: "2026-10-03", weeks: 13, opening: "34800000", buffer: "15000000", rates: { GBP: "1.25", SGD: "0.80" }, delay: 0, receipts: 0, costs: 0, oil: 0, fx: 0 };
function download(text: string, name: string, type: string) {
  const url = URL.createObjectURL(new Blob([text], { type })), link = document.createElement("a");
  link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url);
}
function money(value: string) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(Number(value)); }

export default function PlanningWorkspace() {
  const [phase, setPhase] = useState(1), [furthest, setFurthest] = useState(1);
  function advance(next: number) { setPhase(next); setFurthest(current => Math.max(current, next)); setMessage(""); }
  const [flows, setFlows] = useState<Flow[]>(sampleFlows);
  const [source, setSource] = useState("Fictional energy sample · 3 October 2026");
  const [parsed, setParsed] = useState<ReturnType<typeof parseCsv> | null>(null);
  const [mapping, setMapping] = useState<Mapping>(defaultMapping);
  const [draft, setDraft] = useState<ReturnType<typeof validateRows> | null>(null);
  const [text, setText] = useState("");
  const [filename, setFilename] = useState("");
  const [excelText, setExcelText] = useState("");
  const [inputMethod, setInputMethod] = useState<"sample" | "excel" | "file">("sample");
  const [separator, setSeparator] = useState(",");
  const [message, setMessage] = useState("");
  const [assumptions, setAssumptions] = useState<Assumptions>(defaults);
  const [completed, setCompleted] = useState<{ base: ReturnType<typeof simulate>; stress: ReturnType<typeof simulate>; settings: Assumptions; dataset: Flow[]; source: string } | null>(null);
  const usedCurrencies = [...new Set(flows.map(f => f.currency))].filter(c => c !== "USD");
  const changed = completed && (JSON.stringify(completed.settings) !== JSON.stringify(assumptions) || completed.dataset !== flows);
  const previewRows = useMemo(() => draft?.flows.slice(0, 8) ?? [], [draft]);
  function read(value: string, delimiter = separator) {
    setDraft(null); setMessage("");
    try { const result = parseCsv(value, delimiter); setParsed(result); setMapping(suggestMapping(result.headers)); return true; }
    catch (error) { setParsed(null); setMessage((error as Error).message); return false; }
  }
  return <>
    <div className="demo-notice"><span>◈</span><div><strong>Private planning sandbox · execution disabled</strong><p>Files stay in this browser session. These fresh calculations do not update bank balances, approved forecasts, evidence or payments. Refreshing the page clears your uploaded data.</p></div></div>
    <nav className="planning-steps" aria-label="Cash planning steps">{["Choose data", "Check records", "Set assumptions", "Try a scenario", "Read results"].map((title, i) => <button key={title} aria-current={phase === i + 1 ? "step" : undefined} disabled={i + 1 > furthest || (i === 1 && !parsed)} onClick={() => { setPhase(i + 1); setMessage(""); }}><span>{i + 1}</span>{title}</button>)}</nav>
    <p className="planning-source"><strong>{source.startsWith("Uploaded") ? "Your uploaded data" : "Fictional sample"}</strong> · {source} · no live bank or market feed</p>
    {phase === 1 && <nav className="input-choices" aria-label="Choose a data entry method">{([['sample','Try sample data'],['excel','Paste from Excel'],['file','Upload CSV / TSV']] as const).map(([method,title]) => <button key={method} className="button secondary" aria-pressed={inputMethod === method} onClick={() => { setInputMethod(method); setMessage(""); }}>{title}</button>)}</nav>}
    <article className="panel" hidden={phase !== 1 && phase !== 2}><div className="panel-heading"><h2>{phase === 1 ? "1. Choose your cash-flow data" : "2. Check your records"}</h2><button className="button secondary" onClick={() => download(csvTemplate, "treasury-cashflows-template.csv", "text/csv")}>Download CSV example</button></div><p className="muted">Choose sample data, paste from Excel or upload a CSV/TSV file. Use YYYY-MM-DD dates and plain amounts without currency symbols or thousands separators. Up to 500 records / 512 KB. Native Excel workbook files and PDF statements are not supported yet.</p>
      {phase === 1 && inputMethod === "excel" && <div className="planning-choice"><h3>Copy and paste from Excel</h3><p>Select your table including its column headings in Excel, copy, then paste below. Use reference, due date and amount columns; you can match different heading names in the next step. Copy displayed values, with dates formatted YYYY-MM-DD and amounts without separators. Formula text is not evaluated.</p><div className="workflow-form"><label className="wide">Excel table<textarea rows={6} maxLength={524288} value={excelText} placeholder={"id\tdate\tamount\tdirection\tcurrency\nSALE-01\t2026-10-12\t1000\tINFLOW\tUSD"} onChange={e => setExcelText(e.target.value)} /></label></div><button className="button secondary" disabled={!excelText.trim()} onClick={() => { setSeparator("\t"); setFilename("Copied Excel table"); setText(excelText); if (read(excelText, "\t")) advance(2); }}>Check copied Excel table →</button><p className="muted">Pasted rows stay in this browser session. Validate every row before applying it.</p></div>}
      {phase === 1 && inputMethod === "sample" && <div className="planning-choice"><h3>New here? Try the fictional example first.</h3><p>Use five sample oil-business cash flows. You can adjust the assumptions before running a scenario.</p><button className="button secondary" onClick={() => { setFlows(sampleFlows); setSource("Fictional energy sample · 3 October 2026"); setAssumptions(defaults); setCompleted(null); setParsed(null); setDraft(null); setText(""); setFilename(""); setFurthest(3); advance(3); }}>Use fictional sample →</button></div>}
      {(phase === 2 || inputMethod === "file") && <div className="workflow-form"><label>Choose CSV or TSV<input type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values" onChange={async e => {
        const file = e.target.files?.[0]; if (!file) return;
        setDraft(null); setParsed(null); setMessage(""); setText("");
        if (!/\.(csv|tsv)$/i.test(file.name) || file.size > 524288) { setMessage("Choose a CSV/TSV file under 512 KB. Export Excel workbooks as CSV first."); return; }
        try { const content = await file.text(); const delimiter = /\.tsv$/i.test(file.name) ? "\t" : separator === "\t" ? "," : separator; setSeparator(delimiter); setFilename(file.name); setText(content); if (read(content, delimiter)) advance(2); } catch { setMessage("The file could not be read. Choose it again."); }
      }} /></label><label>Separator<select value={separator} onChange={e => { setSeparator(e.target.value); if (text) read(text, e.target.value); }}><option value=",">Comma</option><option value=";">Semicolon</option><option value={"\t"}>Tab</option></select></label></div>}
      {phase === 2 && parsed && <><p className="muted">{filename} · {parsed.rows.length} records. Match your columns below. Blank currency defaults to USD; blank direction uses the amount sign; blank receipt probability defaults to 1. All payments stay contractual.</p><div className="upload-mapping">{keys.map(key => <label key={key}>{titles[key]}<select value={mapping[key]} onChange={e => { setMapping(previous => ({ ...previous, [key]: e.target.value })); setDraft(null); }}><option value="">{["id", "date", "amount"].includes(key) ? "Choose column" : "Use default"}</option>{parsed.headers.map(h => <option key={h}>{h}</option>)}</select></label>)}</div><button className="button secondary" onClick={() => { const result = validateRows(parsed.rows, mapping); setDraft(result); setMessage(result.errors.length ? "Fix all listed errors before using this dataset." : "Validation passed. Preview the records and choose whether to use them."); }}>Check data</button></>}
      {phase === 2 && draft && <><ul className="bullet-list negative">{draft.errors.slice(0, 20).map((error, i) => <li key={i}>{error}</li>)}</ul>{draft.errors.length > 20 && <p>{draft.errors.length - 20} additional errors. Correct the file and upload again.</p>}{previewRows.length > 0 && <div className="table-scroll"><table><thead><tr><th>Reference</th><th>Date</th><th>Direction</th><th>Currency</th><th>Amount</th><th>Entity</th><th>Category</th></tr></thead><tbody>{previewRows.map(row => <tr key={row.id}><td>{row.id}</td><td>{row.date}</td><td>{row.direction}</td><td>{row.currency}</td><td>{row.amount}</td><td>{row.entity}</td><td>{row.category}</td></tr>)}</tbody></table><p className="muted">Showing the first {previewRows.length} validated records.</p></div>}<button className="button secondary" disabled={draft.errors.length > 0 || draft.flows.length === 0} onClick={() => { setFlows(draft.flows); setAssumptions(a => ({ ...a, opening: "", buffer: "", rates: {}, start: [...draft.flows].map(f => f.date).sort()[0] })); setSource(`Uploaded planning data: ${filename}`); setCompleted(null); setFurthest(3); advance(3); setMessage("Dataset applied only to this planning sandbox. Review opening cash, buffer, dates and exchange-rate assumptions before calculating."); }}>Use checked data in simulator</button></>}
    </article>
    <article className="panel" hidden={phase !== 3}><div className="panel-heading"><h2>3. Set your starting position</h2><button className="button secondary" onClick={() => { setFlows(sampleFlows); setSource("Fictional energy sample · 3 October 2026"); setAssumptions(defaults); setCompleted(null); setParsed(null); setDraft(null); setText(""); setFilename(""); setFurthest(3); advance(3); setMessage("The fictional sample is restored."); }}>Restore fictional sample</button></div><p className="muted">Active dataset: {source} · {flows.length} cash flows. Starting cash and buffer are USD equivalents supplied by you. No credit facilities are assumed.</p><div className="workflow-form">
      <label>Forecast start<input type="date" value={assumptions.start} onChange={e => setAssumptions(a => ({ ...a, start: e.target.value }))} /></label><label>Weeks<input type="number" min="1" max="52" value={assumptions.weeks} onChange={e => setAssumptions(a => ({ ...a, weeks: Number(e.target.value) }))} /></label><label>Opening cash (USD)<input inputMode="decimal" value={assumptions.opening} onChange={e => setAssumptions(a => ({ ...a, opening: e.target.value }))} /></label><label>Minimum cash buffer (USD)<input inputMode="decimal" value={assumptions.buffer} onChange={e => setAssumptions(a => ({ ...a, buffer: e.target.value }))} /></label>
      {usedCurrencies.map(currency => <label key={currency}>Assumed USD per 1 {currency}<input inputMode="decimal" value={assumptions.rates[currency] ?? ""} onChange={e => setAssumptions(a => ({ ...a, rates: { ...a.rates, [currency]: e.target.value } }))} /></label>)}
    </div><p className="muted">Opening cash is what you start with. The cash buffer is the minimum amount you want to keep available.</p><p className="muted">Rates are manual planning assumptions, not live quotes. GBP 1.25 and SGD 0.80 are supplied only for the fictional example; confirm all rates for uploaded data.</p><div className="planning-actions"><button className="button secondary" onClick={() => setPhase(parsed ? 2 : 1)}>← Back to data</button><button className="button secondary" onClick={() => { try { simulate(flows, { ...assumptions, delay: 0, receipts: 0, costs: 0, oil: 0, fx: 0 }); advance(4); } catch (error) { setMessage((error as Error).message); } }}>Continue to scenario →</button></div></article>
    <article className="panel" hidden={phase !== 4}><h2>4. Try a “what if?”</h2><p className="muted">Start with one change, such as customers paying 10 days later. Leave other changes at zero to see that effect clearly.</p><div className="workflow-form">{([['delay','Customer receipt delay (days)',0,90,1],['receipts','Change in receipts (%)',-100,200,0.1],['costs','Change in payments (%)',-100,200,0.1],['oil','Oil-linked cash-flow change (%)',-100,200,0.1],['fx','Change in foreign-currency USD value (%)',-100,200,0.1]] as const).map(([key,title,min,max,step]) => <label key={key}>{title}<input type="number" min={min} max={max} step={step} value={assumptions[key]} onChange={e => setAssumptions(a => ({ ...a, [key]: Number(e.target.value) }))} /></label>)}</div><p className="muted">The oil change applies only to CRUDE_PURCHASE and PRODUCT_SALE rows as a cash amount estimate. It does not price inventory or hedges. FX changes affect future non-USD flows; opening USD cash stays fixed. Separate changes multiply when they apply to the same flow.</p><button className="button secondary" onClick={() => {
      setMessage(""); try { const base = simulate(flows, { ...assumptions, delay: 0, receipts: 0, costs: 0, oil: 0, fx: 0 }); const stress = simulate(flows, assumptions); setCompleted({ base, stress, settings: assumptions, dataset: flows, source }); advance(5); } catch (error) { setCompleted(null); setMessage((error as Error).message); }
    }}>Calculate comparison</button><button className="text-button" onClick={() => setPhase(3)}>← Edit starting position</button></article>
    {message && <p className="planning-feedback" role="status">{message}</p>}
    {completed && <article className="panel" hidden={phase !== 5}><div className="panel-heading"><h2>5. Understand your results</h2><button className="button secondary" disabled={Boolean(changed)} onClick={() => {
      const rows = ["week,week_start,base_closing_usd,scenario_closing_usd,buffer_usd,scenario_shortfall_usd", ...completed.stress.points.map((p, i) => [p.week, p.date, completed.base.points[i].closing, p.closing, p.buffer, p.shortfall].join(","))]; download(rows.join("\n"), "treasury-planning-comparison.csv", "text/csv");
    }}>Download comparison</button></div><div className="planning-result" role="status"><h3>{changed ? "Inputs changed: calculate again to update these results" : completed.stress.firstBreach ? `Cash falls below your minimum target in week ${completed.stress.firstBreach}` : "Cash stays above your minimum target at each weekly close"}</h3><p>{completed.stress.firstBreach ? `The largest gap below your target is ${money(completed.stress.maximumShortfall)}. Compare the weekly timing of receipts and payments below.` : "No weekly closing shortfall appears under these assumptions. This does not rule out shortages within a day or week."}</p></div><div className="planning-actions"><button className="button secondary" onClick={() => setPhase(4)}>Try another scenario</button><button className="button secondary" onClick={() => setPhase(3)}>Edit assumptions</button></div>{changed && <p role="status" className="inline-error">Inputs changed. These results belong to the previous inputs; calculate again.</p>}<p className="muted">{completed.source} · from {completed.settings.start} · {completed.settings.weeks} weeks · computed locally from your planning assumptions</p><div className="metric-grid">{[["Base ending cash",completed.base.ending],["Scenario ending cash",completed.stress.ending],["Scenario maximum shortfall",completed.stress.maximumShortfall],["Scenario ending headroom",completed.stress.headroom]].map(([title,value]) => <div className="metric-card" key={title}><span>{title}</span><strong>{money(value)}</strong></div>)}</div><p className="muted">First scenario buffer breach: {completed.stress.firstBreach ? `week ${completed.stress.firstBreach}` : "none at weekly close"}. {completed.stress.overdue} overdue records and {completed.stress.beyond} records after the horizon were excluded; excluded expected amounts total {money(completed.stress.excludedAmount)}. Weekly closing cash can hide shortages earlier in the week.</p>
      <div className="table-scroll"><table><thead><tr><th>Week</th><th>Starting</th><th>Base cash</th><th>Scenario receipts</th><th>Scenario payments</th><th>Scenario cash</th><th>Buffer</th><th>Shortfall</th></tr></thead><tbody>{completed.stress.points.map((point, i) => <tr key={point.week}><td>{point.week}</td><td>{point.date}</td><td>{money(completed.base.points[i].closing)}</td><td>{money(point.inflows)}</td><td>{money(point.outflows)}</td><td>{money(point.closing)}</td><td>{money(point.buffer)}</td><td className={Number(point.shortfall)>0 ? "negative" : undefined}>{money(point.shortfall)}</td></tr>)}</tbody></table></div></article>}
  </>;
}
