"use client";
import { useMemo, useState } from "react";
import { Assumptions, Flow, Mapping, parseCsv, simulate, validateRows, suggestMapping } from "../lib/planning";
import ForecastReview from "./ForecastReview";

const keys = ["id", "date", "amount", "direction", "currency", "entity", "category", "probability"] as const;
const titles = { id: "Reference *", date: "Due date *", amount: "Amount *", direction: "Inflow / outflow", currency: "Currency", entity: "Entity", category: "Cash-flow category", probability: "Receipt probability" };
const csvTemplate = "id,date,amount,direction,currency,entity,category,probability\nCARGO-01,2026-10-07,18000000,OUTFLOW,USD,Demo UK,CRUDE_PURCHASE,1\nSALE-01,2026-10-10,22000000,INFLOW,USD,Demo UK,PRODUCT_SALE,1\nFREIGHT-01,2026-10-08,1500000,OUTFLOW,USD,Demo UK,FREIGHT,1\nUK-OPS,2026-10-12,1200000,OUTFLOW,GBP,Demo UK,OPERATING,1\nSG-OPS,2026-10-12,2000000,OUTFLOW,SGD,Demo Singapore,OPERATING,1\n";
const defaultMapping = Object.fromEntries(keys.map(k => [k, k])) as Mapping;
const sampleFlows = validateRows(parseCsv(csvTemplate).rows, defaultMapping).flows;
const defaults: Assumptions = { start: "2026-10-03", weeks: 13, opening: "34800000", buffer: "15000000", rates: { GBP: "1.25", SGD: "0.80" }, delay: 0, receipts: 0, costs: 0, oil: 0, fx: 0 };
function download(text: string, name: string, type: string) {
  const url = URL.createObjectURL(new Blob([text], { type })), link = document.createElement("a");
  link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url);
}
function money(value: string) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(Number(value)); }

export default function PlanningWorkspace() {
  const [phase, setPhase] = useState(1), [furthest, setFurthest] = useState(1);
  function advance(next: number) { setPhase(next); setFurthest(current => Math.max(current, next)); setMessage(""); }
  const [flows, setFlows] = useState<Flow[]>(sampleFlows);
  const [source, setSource] = useState("Fictional energy sample · 3 October 2026");
  const [parsed, setParsed] = useState<ReturnType<typeof parseCsv> | null>(null);
  const [mapping, setMapping] = useState<Mapping>(defaultMapping);
  const [draft, setDraft] = useState<ReturnType<typeof validateRows> | null>(null);
  const [text, setText] = useState("");
  const [filename, setFilename] = useState("");
  const [excelText, setExcelText] = useState("");
  const [inputMethod, setInputMethod] = useState<"sample" | "excel" | "file">("sample");
  const [separator, setSeparator] = useState(",");
  const [sheets, setSheets] = useState<{name:string;headers:string[];rows:Record<string,string>[]}[]>([]);
  const [sheetName, setSheetName] = useState("");
  const [importBusy, setImportBusy] = useState(false);
  const [savedVersion, setSavedVersion] = useState<number | null>(null);
  const [canSave, setCanSave] = useState(false), [storageBusy, setStorageBusy] = useState(false);
  const [storageMessage, setStorageMessage] = useState("");
  const [message, setMessage] = useState("");
  const [assumptions, setAssumptions] = useState<Assumptions>(defaults);
  const [completed, setCompleted] = useState<{ base: ReturnType<typeof simulate>; stress: ReturnType<typeof simulate>; settings: Assumptions; dataset: Flow[]; source: string } | null>(null);
  const usedCurrencies = [...new Set(flows.map(f => f.currency))].filter(c => c !== "USD");
  const changed = completed && (JSON.stringify(completed.settings) !== JSON.stringify(assumptions) || completed.dataset !== flows);
  const previewRows = useMemo(() => draft?.flows.slice(0, 8) ?? [], [draft]);
  function read(value: string, delimiter = separator) {
    setDraft(null); setMessage(""); setSheets([]); setSheetName("");
    try { const result = parseCsv(value, delimiter); setParsed(result); setMapping(suggestMapping(result.headers)); return true; }
    catch (error) { setParsed(null); setMessage((error as Error).message); return false; }
  }
  function chooseSheet(name: string, available = sheets) {
    const sheet = available.find(item => item.name === name);
    if (!sheet) return;
    setSheetName(name); setParsed({headers:sheet.headers,rows:sheet.rows});
    setMapping(suggestMapping(sheet.headers)); setDraft(null); advance(2);
  }
  async function storedPlan(write: boolean) {
    setStorageBusy(true); setStorageMessage("");
    try {
      if (write) simulate(flows, assumptions);
      const response = await fetch("/api/planning-draft", {method:write ? "PUT" : "GET", cache:"no-store", headers:{"Content-Type":"application/json"}, ...(write ? {body:JSON.stringify({flows,assumptions,expected_version:savedVersion})} : {}), signal:AbortSignal.timeout(45000)});
      const value = await response.json();
      if (!response.ok) throw Error(value.error ?? "The plan could not be saved or loaded.");
      setSavedVersion(value.draft?.version ?? 0); setCanSave(value.can_edit === true);
      if (!write && value.draft) {
        simulate(value.draft.flows, value.draft.assumptions);
        setFlows(value.draft.flows); setAssumptions(value.draft.assumptions); setSource("Saved company planning draft");
        setCompleted(null); setParsed(null); setDraft(null); setSheets([]); setSheetName(""); setFilename(""); setText(""); setFurthest(3); advance(3);
      }
      setStorageMessage(write ? `Saved company draft version ${value.draft.version}.` : value.draft ? `Loaded draft version ${value.draft.version}.` : "No saved draft yet. Check your data and assumptions before saving.");
    } catch (error) { setStorageMessage((error as Error).message); if (write) {setSavedVersion(null); setCanSave(false);} }
    finally { setStorageBusy(false); }
  }
  return <>
    <div className="demo-notice"><span>◈</span><div><strong>Private planning sandbox · execution disabled</strong><p>Files stay in this browser session until you explicitly save a checked draft to your configured company backend. These fresh calculations do not update bank balances, approved forecasts, evidence or payments. Refreshing the page clears your uploaded data.</p></div></div>
    <details className="panel"><summary>Save or reopen a company plan</summary><p>Requires company sign-in and a configured backend. Loading replaces your current sandbox inputs. Saving sends only the checked cash flows and assumptions to your company database; it never approves a forecast or payment.</p><div className="planning-actions"><button className="button secondary" disabled={storageBusy || importBusy} onClick={() => storedPlan(false)}>Load saved plan / check access</button><button className="button secondary" disabled={storageBusy || importBusy || !canSave || savedVersion === null} onClick={() => storedPlan(true)}>Save current checked plan</button></div><p role="status">{storageBusy ? "Contacting company storage…" : storageMessage}</p></details>
    <nav className="planning-steps" aria-label="Cash planning steps">{["Choose data", "Check records", "Set assumptions", "Try a scenario", "Read results"].map((title, i) => <button key={title} aria-current={phase === i + 1 ? "step" : undefined} disabled={importBusy || i + 1 > furthest || (i === 1 && !parsed)} onClick={() => { setPhase(i + 1); setMessage(""); }}><span>{i + 1}</span>{title}</button>)}</nav>
    <p className="planning-source"><strong>{source.startsWith("Uploaded") ? "Your uploaded data" : source.startsWith("Saved") ? "Saved company draft" : "Fictional sample"}</strong> · {source} · no live bank or market feed</p>
    {phase === 1 && <nav className="input-choices" aria-label="Choose a data entry method">{([['sample','Try sample data'],['excel','Paste from Excel'],['file','Upload Excel / CSV']] as const).map(([method,title]) => <button key={method} className="button secondary" disabled={importBusy} aria-pressed={inputMethod === method} onClick={() => { setInputMethod(method); setMessage(""); }}>{title}</button>)}</nav>}
    {phase === 1 && inputMethod !== "sample" && <details className="panel"><summary>What should my table contain?</summary><p>One row per expected customer payment or bill. The amount is in the row's currency, not automatically in US dollars.</p><div className="table-scroll"><table><thead><tr><th>Column</th><th>What it means</th><th>Example</th></tr></thead><tbody><tr><td>Reference</td><td>A different label for each payment or bill</td><td>SALE-01</td></tr><tr><td>Due Date</td><td>When you expect the money to arrive or leave</td><td>2026-10-12</td></tr><tr><td>Amount</td><td>The money amount, without commas or currency symbols</td><td>1000</td></tr><tr><td>Direction (optional)</td><td>INFLOW means money coming in; OUTFLOW means money going out</td><td>INFLOW</td></tr><tr><td>Currency (optional)</td><td>A currency code; blank assumes US dollars</td><td>USD, INR or EUR</td></tr></tbody></table></div><p>If Direction is blank, a negative amount means money going out. A positive amount means money coming in. Always review these choices before using the data.</p></details>}
    <article className="panel" hidden={phase !== 1 && phase !== 2}><div className="panel-heading"><h2>{phase === 1 ? "1. Choose your cash-flow data" : "2. Check your records"}</h2><div className="planning-actions"><a className="button secondary" href="/treasury-sample.xlsx" download>Download Excel example</a><button className="button secondary" onClick={() => download(csvTemplate, "treasury-cashflows-template.csv", "text/csv")}>Download CSV example</button></div></div><p className="muted">Choose sample data, paste from Excel or upload an XLSX, CSV or TSV file. Use YYYY-MM-DD dates and plain amounts without currency symbols or thousands separators. Up to 500 records / 30 columns. CSV: 512 KB; XLSX: 2 MB. Convert Excel formula cells to values first. PDF statements are not supported.</p>
      {phase === 1 && inputMethod === "excel" && <div className="planning-choice"><h3>Copy and paste from Excel</h3><p>Select your table including its column headings in Excel, copy, then paste below. Use reference, due date and amount columns; you can match different heading names in the next step. Copy displayed values, with dates formatted YYYY-MM-DD and amounts without separators. Formula text is not evaluated.</p><div className="workflow-form"><label className="wide">Excel table<textarea rows={6} maxLength={524288} value={excelText} placeholder={"id\tdate\tamount\tdirection\tcurrency\nSALE-01\t2026-10-12\t1000\tINFLOW\tUSD"} onChange={e => setExcelText(e.target.value)} /></label></div><button className="button secondary" disabled={!excelText.trim()} onClick={() => { setSeparator("\t"); setFilename("Copied Excel table"); setText(excelText); if (read(excelText, "\t")) advance(2); }}>Check copied Excel table →</button><p className="muted">Pasted rows stay in this browser session. Validate every row before applying it.</p></div>}
      {phase === 1 && inputMethod === "sample" && <div className="planning-choice"><h3>New here? Try the fictional example first.</h3><p>Use five sample oil-business cash flows. You can adjust the assumptions before running a scenario.</p><button className="button secondary" onClick={() => { setFlows(sampleFlows); setSource("Fictional energy sample · 3 October 2026"); setAssumptions(defaults); setCompleted(null); setParsed(null); setDraft(null); setSheets([]); setSheetName(""); setText(""); setFilename(""); setFurthest(3); advance(3); }}>Use fictional sample →</button></div>}
      {(phase === 2 || inputMethod === "file") && <div className="workflow-form"><label>Choose Excel, CSV or TSV<input disabled={importBusy} type="file" accept=".xlsx,.csv,.tsv" onChange={async e => {
        const file = e.target.files?.[0]; if (!file) return;
        setDraft(null); setParsed(null); setMessage(""); setText(""); setSheets([]); setSheetName("");
        if (/\.xlsx$/i.test(file.name)) {
          setImportBusy(true);
          try { if (file.size > 2097152) throw Error("Choose an Excel workbook under 2 MB."); const {parseWorkbook} = await import("../lib/spreadsheet-import"); const result = await parseWorkbook(await file.arrayBuffer()); setSheets(result); setFilename(file.name); chooseSheet(result[0].name, result); }
          catch (error) { setMessage((error as Error).message); } finally {setImportBusy(false);}
          return;
        }
        if (!/\.(csv|tsv)$/i.test(file.name) || file.size > 524288) { setMessage("Choose XLSX under 2 MB or CSV/TSV under 512 KB."); return; }
        setImportBusy(true);
        try { const content = await file.text(); const delimiter = /\.tsv$/i.test(file.name) ? "\t" : separator === "\t" ? "," : separator; setSeparator(delimiter); setFilename(file.name); setText(content); if (read(content, delimiter)) advance(2); } catch { setMessage("The file could not be read. Choose it again."); } finally {setImportBusy(false);}
      }} /></label><label>Separator<select disabled={importBusy || sheets.length > 0} value={separator} onChange={e => { setSeparator(e.target.value); if (text) read(text, e.target.value); }}><option value=",">Comma</option><option value=";">Semicolon</option><option value={"\t"}>Tab</option></select></label></div>}
      {importBusy && <p role="status">Reading and checking your file…</p>}
      {phase === 2 && sheets.length > 0 && <label className="company-form">Excel worksheet<select value={sheetName} onChange={event => chooseSheet(event.target.value)}>{sheets.map(sheet => <option key={sheet.name}>{sheet.name}</option>)}</select></label>}
      {phase === 2 && parsed && <><p className="muted">{filename} · {parsed.rows.length} records. Match your columns below. Blank currency defaults to USD; blank direction uses the amount sign; blank receipt probability defaults to 1. All payments stay contractual.</p><div className="upload-mapping">{keys.map(key => <label key={key}>{titles[key]}<select value={mapping[key]} onChange={e => { setMapping(previous => ({ ...previous, [key]: e.target.value })); setDraft(null); }}><option value="">{["id", "date", "amount"].includes(key) ? "Choose column" : "Use default"}</option>{parsed.headers.map(h => <option key={h}>{h}</option>)}</select></label>)}</div><p className="muted">Receipt probability is optional: 1 counts the full expected customer payment; 0.5 counts half in the expected plan. It does not change the actual invoice. Bills must use 1.</p><button className="button secondary" onClick={() => { const result = validateRows(parsed.rows, mapping); setDraft(result); setMessage(result.errors.length ? "Fix all listed errors before using this dataset." : "Validation passed. Preview the records and choose whether to use them."); }}>Check data</button></>}
      {phase === 2 && draft && <><ul className="bullet-list negative">{draft.errors.slice(0, 20).map((error, i) => <li key={i}>{error}</li>)}</ul>{draft.errors.length > 20 && <p>{draft.errors.length - 20} additional errors. Correct the file and upload again.</p>}{previewRows.length > 0 && <div className="table-scroll"><table><thead><tr><th>Reference</th><th>Date</th><th>Direction</th><th>Currency</th><th>Amount</th><th>Entity</th><th>Category</th></tr></thead><tbody>{previewRows.map(row => <tr key={row.id}><td>{row.id}</td><td>{row.date}</td><td>{row.direction === "INFLOW" ? "Money coming in" : "Money going out"}</td><td>{row.currency}</td><td>{row.amount}</td><td>{row.entity}</td><td>{row.category}</td></tr>)}</tbody></table><p className="muted">Showing the first {previewRows.length} validated records.</p></div>}<button className="button secondary" disabled={draft.errors.length > 0 || draft.flows.length === 0} onClick={() => { setFlows(draft.flows); setAssumptions(a => ({ ...a, opening: "", buffer: "", rates: {}, start: [...draft.flows].map(f => f.date).sort()[0] })); setSource(`Uploaded planning data: ${filename}${sheetName ? " · " + sheetName : ""}`); setCompleted(null); setFurthest(3); advance(3); setMessage("Dataset applied only to this planning sandbox. Review opening cash, buffer, dates and exchange-rate assumptions before calculating."); }}>Use checked data in simulator</button></>}
    </article>
    <article className="panel" hidden={phase !== 3}><div className="panel-heading"><h2>3. Set your starting position</h2><button className="button secondary" onClick={() => { setFlows(sampleFlows); setSource("Fictional energy sample · 3 October 2026"); setAssumptions(defaults); setCompleted(null); setParsed(null); setDraft(null); setSheets([]); setSheetName(""); setText(""); setFilename(""); setFurthest(3); advance(3); setMessage("The fictional sample is restored."); }}>Restore fictional sample</button></div><p className="muted">Active dataset: {source} · {flows.length} cash flows. Starting cash and buffer are USD equivalents supplied by you. No credit facilities are assumed.</p><div className="workflow-form">
      <label>First day of your plan<input type="date" value={assumptions.start} onChange={e => setAssumptions(a => ({ ...a, start: e.target.value }))} /></label><label>How many weeks?<input type="number" min="1" max="52" value={assumptions.weeks} onChange={e => setAssumptions(a => ({ ...a, weeks: Number(e.target.value) }))} /></label><label>Money you start with (USD)<input inputMode="decimal" placeholder="For example: 1000" value={assumptions.opening} onChange={e => setAssumptions(a => ({ ...a, opening: e.target.value }))} /></label><label>Minimum money to keep (USD)<input inputMode="decimal" placeholder="For example: 800" value={assumptions.buffer} onChange={e => setAssumptions(a => ({ ...a, buffer: e.target.value }))} /></label>
      {usedCurrencies.map(currency => <label key={currency}>Assumed USD per 1 {currency}<input inputMode="decimal" value={assumptions.rates[currency] ?? ""} onChange={e => setAssumptions(a => ({ ...a, rates: { ...a.rates, [currency]: e.target.value } }))} /></label>)}
    </div><p className="muted">Enter the money available at the start, and the minimum you want to keep. Example: start with 1000 and keep at least 800. All results are shown in US dollars (USD).</p><p className="muted">Rates are manual planning assumptions, not live quotes. GBP 1.25 and SGD 0.80 are supplied only for the fictional example; confirm all rates for uploaded data.</p><div className="planning-actions"><button className="button secondary" onClick={() => setPhase(parsed ? 2 : 1)}>← Back to data</button><button className="button secondary" onClick={() => { try { simulate(flows, { ...assumptions, delay: 0, receipts: 0, costs: 0, oil: 0, fx: 0 }); advance(4); } catch (error) { setMessage((error as Error).message); } }}>Continue to scenario →</button></div></article>
    <article className="panel" hidden={phase !== 4}><h2>4. Try a “what if?”</h2><p className="muted">Start with one change, such as customers paying 10 days later. Zero means no change. A 10% payment increase turns a 500 bill into 550; a -10% change turns it into 450.</p><div className="workflow-form">{([['delay','Customer receipt delay (days)',0,90,1],['receipts','Change in receipts (%)',-100,200,0.1],['costs','Change in payments (%)',-100,200,0.1],['oil','Oil-linked cash-flow change (%)',-100,200,0.1],['fx','Change in foreign-currency USD value (%)',-100,200,0.1]] as const).map(([key,title,min,max,step]) => <label key={key}>{title}<input type="number" min={min} max={max} step={step} value={assumptions[key]} onChange={e => setAssumptions(a => ({ ...a, [key]: Number(e.target.value) }))} /></label>)}</div><p className="muted">The oil change applies only to CRUDE_PURCHASE and PRODUCT_SALE rows as a cash amount estimate. It does not price inventory or hedges. FX changes affect future non-USD flows; opening USD cash stays fixed. Separate changes multiply when they apply to the same flow.</p><button className="button secondary" onClick={() => {
      setMessage(""); try { const base = simulate(flows, { ...assumptions, delay: 0, receipts: 0, costs: 0, oil: 0, fx: 0 }); const stress = simulate(flows, assumptions); setCompleted({ base, stress, settings: assumptions, dataset: flows, source }); advance(5); } catch (error) { setCompleted(null); setMessage((error as Error).message); }
    }}>Calculate comparison</button><button className="text-button" onClick={() => setPhase(3)}>← Edit starting position</button></article>
    {message && <p className="planning-feedback" role="status">{message}</p>}
    {completed && <article className="panel" hidden={phase !== 5}><div className="panel-heading"><h2>5. Understand your results</h2><button className="button secondary" disabled={Boolean(changed)} onClick={() => {
      const rows = ["week,week_start,base_closing_usd,scenario_closing_usd,buffer_usd,scenario_shortfall_usd", ...completed.stress.points.map((p, i) => [p.week, p.date, completed.base.points[i].closing, p.closing, p.buffer, p.shortfall].join(","))]; download(rows.join("\n"), "treasury-planning-comparison.csv", "text/csv");
    }}>Download comparison</button></div><div className="planning-result" role="status"><h3>{changed ? "Inputs changed: calculate again to update these results" : completed.stress.firstBreach ? `Cash falls below your minimum target in week ${completed.stress.firstBreach}` : "Cash stays at or above your minimum target at each weekly close"}</h3><p>{completed.stress.firstBreach ? `The largest gap below your target is ${money(completed.stress.maximumShortfall)}. Compare the weekly timing of receipts and payments below.` : "At each week end, the plan stays at or above your chosen minimum. You could still run short earlier in a day or week."}</p></div><div className="planning-actions"><button className="button secondary" onClick={() => setPhase(4)}>Try another scenario</button><button className="button secondary" onClick={() => setPhase(3)}>Edit assumptions</button></div>{changed && <p role="status" className="inline-error">Inputs changed. These results belong to the previous inputs; calculate again.</p>}<p className="muted">{completed.source} · from {completed.settings.start} · {completed.settings.weeks} weeks · computed locally from your planning assumptions</p><div className="metric-grid">{[["Money left without changes",completed.base.ending],["Money left after your changes",completed.stress.ending],["Biggest gap below your minimum",completed.stress.maximumShortfall],["Amount above or below minimum at the end",completed.stress.headroom]].map(([title,value]) => <div className="metric-card" key={title}><span>{title}</span><strong>{money(value)}</strong></div>)}</div><p className="muted">First week below your minimum: {completed.stress.firstBreach ? `week ${completed.stress.firstBreach}` : "no week below your minimum"}. {completed.stress.overdue} overdue records and {completed.stress.beyond} records after the horizon were excluded; excluded expected amounts total {money(completed.stress.excludedAmount)}. Weekly closing cash can hide shortages earlier in the week.</p>
      <div className="table-scroll"><table><thead><tr><th>Week</th><th>Week starting</th><th>Money left without changes</th><th>Money coming in</th><th>Money going out</th><th>Money left after changes</th><th>Minimum to keep</th><th>Gap below minimum</th></tr></thead><tbody>{completed.stress.points.map((point, i) => <tr key={point.week}><td>{point.week}</td><td>{point.date}</td><td>{money(completed.base.points[i].closing)}</td><td>{money(point.inflows)}</td><td>{money(point.outflows)}</td><td>{money(point.closing)}</td><td>{money(point.buffer)}</td><td className={Number(point.shortfall)>0 ? "negative" : undefined}>{money(point.shortfall)}</td></tr>)}</tbody></table></div></article>}
    {completed && phase === 5 && !changed && <ForecastReview points={completed.base.points} source={completed.source} />}
  </>;
}
