export type Guide = { title: string; steps: string[] };
export const guides: Record<string, Guide> = {
  automatic: { title: "Watch dummy automatic updates", steps: ["Choose Operating structure: a single-country company can have foreign-currency transactions, while an MNC shows entities in several countries. Changing structure restarts the dummy feed.", "Start automatic updates to process the next fictional bank, invoice or FX event five seconds after each refresh. Cash, forecasts and hedge coverage are recalculated together.", "For an MNC, compare local entity cash with USD group totals. A group surplus can hide an entity shortage; consolidated cash does not authorize transfers.", "Inspect the event history: duplicates are ignored and invalid messages are quarantined. Failed market refreshes retain visibly labelled last validated prices.", "This runs only while the workspace is open. All data is fictional; no confidential uploads, live feeds, trades, payments or source activation are involved."] },
  company: { title: "Set up your company", steps: ["Register the company profile, then register legal entities for review. Saving requires an authenticated Group Treasurer.", "Pending registrations do not enter treasury calculations. Connect verified data and provision staff roles through your operator.", "Each company needs its own deployment and database. The public demo cannot save company records or clear production gates."] },
  start: { title: "Choose what you want to do", steps: ["Open Company setup to register your business and review entities and staff roles. The energy demo remains available under More reports.", "Start cash planning to choose data, check records, set assumptions, try a scenario and read the results.", "Review readiness to see missing evidence and human sign-offs before real execution."] },
  overview: { title: "Start with your cash picture", steps: ["Read deployable cash, the cash buffer and the 13-week ending cash together.", "A dash means data is unavailable, not zero. Loading means the report is pending; Unavailable offers Retry workspace. Refresh workspace reloads the reports.", "Check the data label: the public demo shows recorded synthetic results."] },
  forecast: { title: "Read the cash forecast", steps: ["Compare weekly closing cash with the minimum buffer.", "A shortfall means cash falls below the configured buffer; ending cash alone can hide earlier gaps.", "Weekly figures do not show every shortage within a day or week."] },
  energy: { title: "Explore the fictional oil business", steps: ["Choose Base, Receipt Delay, Cargo Cost Up, USD Funding Pressure or Combined to compare recorded scenarios.", "Look at maximum buffer shortfall and the first breach week.", "These are fictional UK and Singapore cash flows, not Shell company data or live oil prices."] },
  planning: { title: "Upload, check, then try a scenario", steps: ["Download the CSV example, or export your spreadsheet as UTF-8 CSV. Native XLSX and PDF are unsupported.", "Choose your file, map reference/date/amount, then Check data. Fix every error before using the preview.", "Choose Use checked data in simulator. Enter opening USD cash, buffer, dates and any manual FX rates.", "Choose Continue to scenario. Change receipt delays, payments, oil-linked cash flows or FX, then Calculate comparison. Download the results after recalculating."] },
  risk: { title: "Understand risk reports", steps: ["Review FX hedges, derivative exposure, interest rates and counterparties.", "Read the warnings and data-source labels alongside the numbers.", "Expand the report details and read source warnings. Coverage and residual exposure are not predicted losses or VaR; the guide cannot place trades or recommend a hedge."] },
  funding: { title: "Find where cash can move", steps: ["Review entity cash, funding concentration and mobility constraints.", "Group cash may be unavailable to another entity because of local restrictions.", "Transfers require the relevant treasury, legal and tax reviews."] },
  integrations: { title: "Check the quality of source data", steps: ["Review mapping, reconciliation, freshness and source authority.", "SHADOW means the source is being checked; ACTIVE requires the configured gates and human promotion.", "A working connector alone does not certify bank or ERP data."] },
  governance: { title: "Review evidence and governed decisions", steps: ["Read the controlled go-live gate and its missing evidence. Company sign-in and a configured backend are required; public demo writes are disabled.", "In Release evidence & decisions, enter a Release number and choose Review release. Inspect state, readiness, blockers and Audit trail before choosing a Task.", "Register a release candidate requires the Group Treasurer, a release name and SHA-256 fingerprints for candidate and rollback artifacts. Other tasks require a loaded release.", "Record review evidence requires your assigned Review gate, Evidence source, result, reference, scope, validity date, document fingerprint and gate-specific JSON. Fingerprint a document hashes it locally; the document is not uploaded. Dummy evidence stays SYNTHETIC and cannot replace required real evidence.", "Record a parallel-run comparison requires an eligible analyst or integration owner, observation date, measure, scope, incumbent/platform values and evidence fingerprint. A comparison alone does not clear readiness.", "Submit your sign-off uses your permitted independent role and the loaded evidence fingerprint. Review your decision and reason; evidence changes invalidate earlier sign-offs.", "Record a release decision requires a permitted Group Treasurer or Operations Manager. START_PARALLEL, HALT, ROLLBACK and GO_LIVE remain backend-checked decisions; they do not deploy software, restore a database or send payments. Missing evidence cannot be assumed passed."] },
  agents: { title: "Meet the five reasoning teams", steps: ["The five teams cover liquidity, market risk, global treasury, governance and orchestration.", "Deterministic engines calculate the numbers; AI supports interpretation and humans approve actions.", "Live AI requires configured model access. Mint is a built-in app guide and does not call a model."] },
  analytics: { title: "Find a specialist analysis", steps: ["Search a topic such as liquidity, collateral or forecasts.", "Choose Analysis to load its report. Search filters choices but preserves the current selection until you change it.", "Check warnings and missing-data messages before using the output."] },
};
const workspaceQuestions: Record<string, string[]> = {
  start: ["Where do I start?", "How do automatic updates work?", "How do I upload a CSV?"],
  company: ["How do I set up my company?", "Why is company setup disabled?", "How do I sign in?"],
  automatic: ["How do automatic updates work?", "Explain operating structure", "What does hedge coverage mean?"],
  overview: ["What does deployable cash mean?", "What does headroom mean?", "How do I refresh this workspace?"],
  forecast: ["How do I read the cash forecast?", "What does shortfall mean?", "What is forecast accuracy?"],
  energy: ["How do I use the energy pilot?", "What does Combined mean?", "Is this real company data?"],
  planning: ["How do I upload a CSV?", "How do I run a simulation?", "Why is Download comparison disabled?"],
  risk: ["What does hedge coverage mean?", "Is residual exposure a predicted loss?", "How do I read risk reports?"],
  funding: ["How do I read cash mobility?", "Can group cash cover an entity shortage?", "What is funding concentration?"],
  integrations: ["What does SHADOW mean?", "What is reconciliation?", "Why is source activation blocked?"],
  governance: ["How do I record release evidence?", "Why is Submit record disabled?", "Does rollback restore the application?"],
  agents: ["How do the AI teams work?", "Does Mint call a model?", "Can AI approve a payment?"],
  analytics: ["How do I search the analysis library?", "Why is the selected analysis still shown?", "How do I retry an unavailable analysis?"],
};
export function suggestedQuestions(view?: string): string[] { return [...(workspaceQuestions[view ?? ""] ?? workspaceQuestions.start)]; }
export const tour = [
  { view: "start", title: "1. Choose a task", text: "Start here offers Company setup, Cash planning and readiness. More reports opens specialist workspaces." },
  { view: "company", title: "2. Register your company", text: "Register a profile and pending entities. A hosted backend and Group Treasurer sign-in are required to save; registration does not activate data." },
  { view: "automatic", title: "3. Watch dummy updates", text: "Choose Operating structure, then Start automatic updates. Pause or process one event. MNC group cash does not authorize entity transfers." },
  { view: "overview", title: "4. Read today's cash picture", text: "Read deployable cash, buffer and headroom. Compare cash by legal entity; a dash means unavailable data." },
  { view: "forecast", title: "5. Check weekly cash pressure", text: "Compare closing cash and the buffer across the forecast, then inspect stress, accuracy and drivers. Weekly closes can hide intraday gaps." },
  { view: "energy", title: "6. Compare energy scenarios", text: "Choose Base, Receipt Delay, Cargo Cost Up, USD Funding Pressure or Combined. All are recorded fictional oil-business scenarios." },
  { view: "planning", title: "7. Try your own cash plan", text: "Choose a CSV/TSV, map columns, Check data and apply checked records. Set opening cash, buffer and FX assumptions, Continue to scenario, Calculate comparison and download results." },
  { view: "risk", title: "8. Review risk reports", text: "Review FX coverage, derivatives, interest rates and counterparties. Residual exposure is not a predicted loss; the guide cannot approve a hedge." },
  { view: "funding", title: "9. Check cash availability", text: "Review cash mobility, funding concentration, cross-border constraints and survival. Group surplus can hide local shortages." },
  { view: "integrations", title: "10. Verify source quality", text: "Review mappings, reconciliation, freshness and authority. SHADOW stays excluded until required gates and human promotion pass." },
  { view: "governance", title: "11. Review evidence and decisions", text: "Review go-live blockers. Authenticated staff can record release evidence within their roles; synthetic evidence cannot replace required real evidence." },
  { view: "agents", title: "12. Understand the five teams", text: "Deterministic engines calculate, five AI teams support interpretation and humans approve. Mint uses built-in guidance, with no model call." },
  { view: "analytics", title: "13. Find a specialist report", text: "Search an analysis name and choose Analysis to load it. Read warnings, expand details and use Retry workspace if loading fails." },
];
export type HelpContext = { view?: string; topic?: string; recordedDemo?: boolean };
export type HelpAnswer = { text: string; view?: string; topic: string; suggestions: string[] };
const topics: Record<string, { view: string; terms: string[]; text: string; detail: string; example: string; suggestions: string[] }> = {
  automatic: { view: "automatic", terms: ["automatic updates", "automated updates", "dummy feed", "auto update", "bank events", "automation", "operating structure", "single-country", "single country", "multinational", "mnc", "group cash", "entity cash", "available local cash", "pause updates", "restart dummy"], text: guides.automatic.steps.join(" "), detail: "The server recalculates synthetic cash, forecasts and open FX exposure from a fixed dummy event sequence. Existing hedge notionals stay unchanged; this is not trade execution, live model reasoning or a 24-hour scheduler. Other dashboard reports remain recorded demonstrations. MNC entity cash uses local functional currencies, while group figures report in USD. Cash pooling, intercompany funding and cross-border transfers require separate legal, tax and human approvals.", example: "A new EUR payable can reverse net currency exposure, leaving an existing SELL hedge in the wrong direction. The screen raises a review alert; it does not change or place a hedge.", suggestions: ["Explain this screen", "Why is go-live blocked?"] },
  company: { view: "company", terms: ["set up my company", "company setup", "register company", "business setup", "onboarding", "legal entity", "staff roles"], text: guides.company.steps.join(" "), detail: "The authenticated Group Treasurer saves profile metadata and pending legal-entity registrations with an audit trail. Reporting currency is deployment configuration. Pending registrations do not enter treasury engines, grant roles or clear go-live gates.", example: "A manufacturing company can register its profile and an Indian subsidiary with INR functional currency. The operator must separately review entity configuration, currency support, bank mappings and evidence before live use.", suggestions: ["Explain this screen", "Why is go-live blocked?"] },
  overview: { view: "overview", terms: ["deployable cash", "cash dashboard", "treasury at a glance"], text: "Open Dashboard and read deployable cash, cash buffer, liquidity headroom and 13-week ending cash together. Deployable cash reflects restrictions and commitments; headroom follows this report’s cash and eligible-credit calculation. Review Cash by legal entity and control signals. A dash means missing data, not zero.", detail: "Explore opens Cash forecast. Refresh workspace retries the dashboard reports. Expand nested report details where available and check the source label; recorded synthetic results are not a current company position. Group totals do not establish local cash availability.", example: "A positive group headroom can coexist with an entity below its own cash buffer. Check both the group cards and Cash by legal entity.", suggestions: ["What does headroom mean?", "How do I refresh this workspace?"] },
  risk: { view: "risk", terms: ["hedge coverage", "residual exposure", "fx exposure", "var", "predicted loss", "risk reports", "derivative risk", "interest rate risk", "counterparty risk"], text: "Open Risks and review hedge coverage alongside derivative, interest-rate and counterparty reports. Coverage compares hedge notionals with open currency exposure. Check signs and review status: an opposite direction is needed to offset exposure. Residual exposure is not predicted loss or VaR. Read each report's warnings and source label.", detail: "The dummy Automatic updates example checks a 60–90% hedge range; that is not a universal company policy. A coverage percentage alone can hide a hedge in the wrong direction. VaR is a separate modelled risk measure with assumptions and limits, not a guaranteed worst-case loss. Mint cannot inspect positions or recommend a trade.", example: "Illustration: EUR 100 receipts plus an existing SELL hedge of EUR 60 leave EUR 40 residual exposure. A BUY hedge would increase that exposure. This is arithmetic, not a trade recommendation.", suggestions: ["Explain this screen", "Is this live company data?"] },
  funding: { view: "funding", terms: ["cash mobility", "funding concentration", "cross-border", "liquidity survival", "entity shortage", "funding reports", "cash pooling"], text: "Open More reports → Funding & entities. Review cash mobility and local constraints before comparing funding concentration, the cross-border graph and liquidity survival. Group cash is a consolidated figure; an entity may still lack usable cash. Transfers require treasury, legal and tax review.", detail: "Funding concentration shows reliance on particular funding sources. Survival estimates depend on the report's assumptions and available funding; they do not promise solvency. Expand report details and warnings. This screen reports constraints and does not move money or arrange a facility.", example: "A group may have a cash surplus while a subsidiary is below its buffer. Restricted cash elsewhere does not automatically fund that subsidiary.", suggestions: ["Explain this screen", "Why is go-live blocked?"] },
  analytics: { view: "analytics", terms: ["analysis library", "specialist analysis", "analysis search", "search analyses", "search an analysis", "selected analysis", "find a report"], text: "Open More reports → Analysis library. Type a topic in Find a specialist analysis, then choose an Analysis to load its report. Searching filters available choices; it does not select a new report. The currently selected analysis stays listed even when it does not match the search. Expand details and read warnings.", detail: "If no new choices appear, shorten the search or clear it. Use Refresh workspace or Retry workspace when the chosen report is unavailable. Mint does not inspect the report's values or invent missing results.", example: "Search collateral, then select a matching analysis. Merely typing collateral leaves the previous report selected until you change Analysis.", suggestions: ["Explain this screen", "How do I retry an unavailable analysis?"] },
  energy: { view: "energy", terms: ["energy pilot", "combined", "cargo cost up", "usd funding pressure", "receipt delay scenario"], text: "Open More reports → Energy pilot and choose Base, Receipt Delay, Cargo Cost Up, USD Funding Pressure or Combined. Compare maximum buffer shortfall and first breach week, then read the weekly cash outlook. These buttons select recorded fictional scenarios; they do not refresh oil prices or change your company data.", detail: "Combined applies the supplied stress assumptions together. Compare it with Base and the individual stresses to see timing pressure. Check local entity warnings as well as group totals. The pilot models cash flows, not commodity inventory or hedge valuations.", example: "Select Receipt Delay, then Combined and compare the first breach week and maximum shortfall. A positive ending balance can still hide earlier weekly gaps.", suggestions: ["Explain this screen", "What does shortfall mean?"] },
  forecast: { view: "forecast", terms: ["cash forecast", "forecast accuracy", "forecast drivers", "weekly cash outlook", "stress summary"], text: "Open More reports → Cash forecast. Compare each week's closing cash with the minimum buffer, then review stress, accuracy and driver reports. Expand the weekly points for exact values. Refresh workspace reloads the selected reports; public demo results remain recorded synthetic snapshots.", detail: "Accuracy reports compare forecasts with available observations; inspect their sample and warnings rather than assuming a forecast is reliable. Drivers explain reported contributors. Weekly closing balances do not establish intraday solvency or cash availability in every entity.", example: "If week 2 closes below the buffer but week 13 ends above it, review the week 2 funding gap. Ending cash alone does not remove that earlier shortage.", suggestions: ["What does shortfall mean?", "How do I refresh this workspace?"] },
  access: { view: "governance", terms: ["sign in", "sign-in", "login", "account access", "staff access"], text: "Use Company sign-in in the top bar when available. Company sign-in awaiting setup means an operator must configure the hosted backend and identity provider; Mint cannot enable it. Your verified company account determines your role. The public recorded demo cannot save or approve records.", detail: "For a failed sign-in, verify your company account access with your operator. Mint cannot grant roles, create verified accounts or bypass authorization. A Group Treasurer can save company setup; release tasks require their assigned roles and a loaded release. Signing in does not clear production evidence gates.", example: "If Submit record says your assigned role cannot submit this task, ask the operator to verify provisioning. Choosing another Task does not grant access.", suggestions: ["Why is Submit record disabled?", "Why is go-live blocked?"] },
  troubleshooting: { view: "overview", terms: ["refresh workspace", "refresh", "retry workspace", "retry", "unavailable analysis", "connection interrupted", "missing data", "dash", "disabled", "cannot click", "button not working"], text: "Read the message next to the control. For an unavailable report, use Retry workspace or Refresh workspace. A dash means missing data, not zero. A disabled action can mean loading, missing inputs, required sign-in, insufficient role or a production gate; Mint cannot bypass it.", detail: "Share the screen name and exact field or error message for specific built-in guidance. Do not remove legitimate records or treat missing evidence as passed to enable a control.", example: "An unavailable cash report shows a dash. Retry it; do not interpret the dash as a zero balance.", suggestions: ["Explain this screen", "How do I sign in?"] },
  upload: { view: "planning", terms: ["upload", "csv", "xlsx", "excel", "pdf", "columns", "mapping", "map", "spreadsheet", "file format"], text: "Export your sheet as UTF-8 CSV or TSV. Choose the file in Choose data, match reference, due date and amount columns in Check records, then Check data. Preview the rows before choosing Use checked data in simulator. Enter your opening cash, buffer and FX assumptions after applying the file.", detail: "Use unique references, valid YYYY-MM-DD dates and plain amounts with at most two decimals. Optional columns include direction, currency, entity, category and receipt probability. Limits are 500 records, 30 columns and 512 KB. Native Excel workbooks and PDFs are unsupported.", example: "Example CSV row: SALE-01,2026-10-10,1000,INFLOW,USD. Use headers id,date,amount,direction,currency. A negative signed amount without a direction is treated as an outflow.", suggestions: ["My file has an error", "How do I run a simulation?"] },
  validation: { view: "planning", terms: ["duplicate", "invalid", "validation", "file error", "upload error", "file has an error", "date error", "format error", "missing rate", "missing fx", "exchange rate error"], text: "Read the record number and error from Check data. Fix the original file and upload it again; one invalid record blocks application of the entire dataset. Duplicate references need unique IDs. Dates must be real YYYY-MM-DD dates, and amounts must have no commas or currency symbols.", detail: "For a missing exchange rate, enter Assumed USD per 1 currency under Set your starting position. Applying a file deliberately clears the fictional cash, buffer and FX assumptions. Crude purchases must be outflows, product sales inflows, and payments must have probability 1.", example: "A date such as 2026-02-30 is invalid. Two rows both called SALE-01 are duplicates. Use separate business references; do not delete legitimate transactions just to make the check pass.", suggestions: ["Show a CSV example", "What assumptions do I need?"] },
  assumptions: { view: "planning", terms: ["assumptions", "opening cash", "starting cash", "starting position", "manual rate", "fx rates", "exchange rates"], text: "Enter opening cash and the minimum buffer as USD equivalents, then choose the start date and 1–52 forecast weeks. For each non-USD currency, enter how many US dollars equal one unit of that currency. Rates are your manual assumptions, not live prices.", detail: "No credit facilities are included in this planner. The entity column labels cash flows; this planner aggregates them in USD against one opening cash balance and buffer. It does not calculate separate entity cash availability or authorize cash pooling. FX shocks change future non-USD flows while opening USD cash stays fixed. Overdue and post-horizon flows are excluded and reported separately. Set every assumption before calculating.", example: "If one GBP is assumed to equal USD 1.25, enter 1.25 for GBP. This is an example rate, not a current market quote.", suggestions: ["How do I run a simulation?", "What is a cash buffer?"] },
  simulation: { view: "planning", terms: ["simulate", "simulation", "simulator", "what if", "what-if", "delay", "scenario", "oil", "shock", "recalculate"], text: "In Cash planning, set your starting position, choose Continue to scenario, adjust a receipt delay or percentage change, then Calculate comparison. Compare base and scenario cash week by week, especially maximum shortfall and the first buffer breach. Recalculate after editing inputs.", detail: "Receipt delays range from 0 to 90 days. Percentage changes range from -100% to +200% in 0.1% steps. Applicable changes multiply. Oil changes adjust crude-purchase and product-sale cash amounts; they do not value inventory or hedges. Weekly closing cash can hide intraday gaps.", example: "Try the fictional sample with a 10-day receipt delay and other shocks at zero: ending cash stays USD 34.2 million, but the scenario has a USD 2.8 million shortfall in week 2. This is a synthetic example, not a prediction for your company.", suggestions: ["What does shortfall mean?", "How do I download results?"] },
  buffer: { view: "forecast", terms: ["shortfall", "headroom", "buffer", "forecast", "cash gap", "negative cash", "liquidity"], text: "The cash buffer is the minimum cash target. In the private planner, headroom is weekly closing cash minus the buffer. Negative headroom becomes a shortfall. Check every week: a good ending balance can hide an earlier shortage.", detail: "The overview liquidity report may also include eligible facilities and other engine-specific adjustments; read its fields rather than assuming every report uses the planner formula. Weekly values do not establish intraday solvency or cash availability in each legal entity.", example: "Illustration: USD 12 million closing cash with a USD 15 million buffer gives minus USD 3 million headroom and a USD 3 million shortfall. This example uses the private planner's formula.", suggestions: ["How do I run a simulation?", "Explain this screen"] },
  privacy: { view: "planning", terms: ["privacy", "private", "stored", "save", "saved", "sent", "secure", "reload", "refresh page", "page refresh", "remember", "memory"], text: "Planning files and this help conversation stay in browser memory. Moving between workspaces preserves them during the session; reloading clears them. Mint does not send questions or uploaded file contents to an AI service.", detail: "The planner does not write to approved forecasts, bank balances, release evidence or payments. Downloaded CSVs are files on your device and are not deleted by refreshing. Clear conversation removes Mint's session history without changing your planning dataset.", example: "If you reload the page after uploading a file, you will need to choose it again. If you download a comparison, that exported file remains on your device.", suggestions: ["How do I download results?", "Is this live company data?"] },
  export: { view: "planning", terms: ["download", "export", "comparison csv", "results file"], text: "After Calculate comparison, choose Download comparison to save weekly base/scenario closing cash, buffer and scenario shortfall as CSV. If you change inputs, the export is disabled until you calculate again.", detail: "Download CSV example gives you a fictional input template; Download comparison exports results. These are different files. Exports contain calculated values, not a certification or permission to execute payments.", example: "Change a receipt delay from 0 to 10 days, calculate again, then download. The CSV should match the newly displayed scenario.", suggestions: ["How do I upload a CSV?", "Where are my files stored?"] },
  governance: { view: "governance", terms: ["go live", "go-live", "production", "blocked", "approval", "approve", "certification", "certified", "release evidence", "release decision", "parallel run", "incumbent", "document fingerprint", "sha-256", "evidence digest", "audit trail", "review gate", "sign off", "rollback", "roll back", "parallel-run", "sign-off", "signoff", "real data", "live data", "company data", "bank connection"], text: "Review the readiness blockers, then enter a Release number and Review release. Choose a Task for evidence, comparison, sign-off or a release decision; your verified role and the current evidence determine what is allowed. The public demo cannot save records. Missing evidence cannot be assumed passed.", detail: "In Release evidence & decisions, enter a Release number and Review release before selecting Task. Record review evidence stores a document fingerprint and reference, not the document itself. Evidence changes invalidate earlier sign-offs. START_PARALLEL, HALT, ROLLBACK and GO_LIVE record governed decisions; they do not deploy software, restore databases or send payments. A working website or connector does not clear production gates. Real bank/ERP feeds, independent model validation, security and recovery evidence, UAT and role-based human sign-offs remain separate requirements. Do not treat unavailable evidence as passed.", example: "A SHADOW source can be connected for validation while still being excluded from authoritative calculations. It needs its configured gates and human promotion before becoming ACTIVE.", suggestions: ["What does SHADOW mean?", "How do the AI teams work?"] },
  integrations: { view: "integrations", terms: ["shadow", "active", "reconciliation", "source", "connector", "erp", "integration"], text: guides.integrations.steps.join(" "), detail: "Compare completeness, timeliness, validity, uniqueness and reconciliation. A missing mapping or failed check should remain visible as quarantine or blocking evidence, rather than silently entering treasury calculations.", example: "An unmapped bank account needs a reviewed internal mapping before its records can be accepted. Source activation remains a human-controlled decision.", suggestions: ["Why is go-live blocked?", "Is this live company data?"] },
  agents: { view: "agents", terms: ["agent", "agents", "gpt", "model", "ai", "teams", "artificial intelligence"], text: guides.agents.steps.join(" "), detail: "The architecture preserves five GPT-6 Astra reasoning teams with token-efficient routing. This guide is separate from those teams. It uses curated rules and session context; there is no live GPT call or claim of model-generated analysis here.", example: "Use Mint to learn where a report is and how to read its fields. Use the treasury workflow for calculations, evidence review and human decisions.", suggestions: ["Explain this screen", "Why is go-live blocked?"] },
};
function result(topic: string, mode: "normal" | "detail" | "example" = "normal", context: HelpContext = {}): HelpAnswer {
  const item = topics[topic];
  if (topic === "troubleshooting" && context.view && guides[context.view]) {
    const recovery: Record<string, string> = {
      planning: "Use checked data in simulator stays disabled until every record is valid. Later steps unlock in order. Download comparison stays disabled after input changes: return to Try a scenario and Calculate comparison again. For missing FX, enter Assumed USD per 1 currency under Set your starting position.",
      automatic: "Start needs an initial snapshot and stops when the dummy feed finishes. Pause remains available while running. After a failed refresh, positions retain the last successful snapshot; retry with Process next dummy event. Use Retry initial snapshot if nothing has loaded, or Restart dummy example after completion.",
      company: "Company setup is disabled in the public recorded demo. A connected deployment needs company sign-in and the Group Treasurer role. Wait for Loading to finish. Register a legal entity also needs a saved company profile; pending registration does not activate it.",
      governance: "Submit record needs company sign-in, the permitted role and a loaded release, except when registering a new candidate. Enter a Release number and Review release first. Read blockers and the role message; synthetic evidence does not replace required real evidence. Mint cannot enable or approve the action.",
    };
    return { topic, view: context.view, text: recovery[context.view] ?? item.text, suggestions: suggestedQuestions(context.view) };
  }
  return { topic, view: item.view, text: mode === "detail" ? item.detail : mode === "example" ? item.example : item.text, suggestions: item.suggestions };
}
export function answerHelp(question: string, context: HelpContext = {}): HelpAnswer {
  const q = question.trim().toLowerCase().replace(/[’']/g, "").replace(/[^a-z0-9-]+/g, " ").trim();
  const has = (phrase: string) => (` ${q} `).includes(` ${phrase} `);
  if (/^(how (do|can)|where|what steps)\b/.test(q) && /\b(approve|activate|roll back|rollback)\b/.test(q) && /\b(release|source)\b/.test(q)) return result(/\bsource\b/.test(q) ? "integrations" : "governance", "detail", context);
  if (/\b(buy|sell|execute|place|send|approve|activate)\b/.test(q) && /\b(trade|hedge|payment|transfer|release|source)\b/.test(q)) return { topic: "boundary", view: "governance", text: "I can explain app controls and reports, but I cannot execute or approve trades, payments, transfers, releases or source activation. Those actions stay in the governed workflow with the required human roles and evidence.", suggestions: ["Why is go-live blocked?", "Explain this screen"] };
  if (["explain this screen", "this screen", "what can i do here", "what next", "what now", "where do i start"].some(has)) {
    const view = context.view && guides[context.view] ? context.view : "overview";
    return { topic: `screen:${view}`, view, text: `${guides[view].title}. ${guides[view].steps.join(" ")}`, suggestions: suggestedQuestions(view) };
  }
  if (context.view === "automatic" && /\b(live|real)\b/.test(q) && /\b(data|numbers|results|company)\b/.test(q)) return { topic: "automatic", view: "automatic", text: "These are freshly calculated dummy positions from fictional bank, invoice and market events. They are not real company data, live provider prices or live AI analysis. Other dashboard reports remain recorded demonstrations.", suggestions: ["Explain this screen", "Why is go-live blocked?"] };
  if (/\b(live|real)\b/.test(q) && /\b(data|numbers|results|company)\b/.test(q)) return { topic: "governance", view: "governance", text: context.recordedDemo === false ? "This screen is connected to the configured backend. Check its source authority, timestamps and production gates; a backend connection does not prove all sources are real, fresh or approved. The private planner still uses your local assumptions." : "The public dashboard shows recorded synthetic results. The private planner calculates fresh results from the sample or your uploaded file, but has no live market feed. Mint does not have a live GPT connection.", suggestions: ["Why is go-live blocked?", "What assumptions do I need?"] };
  const ranked = Object.entries(topics).map(([key, item]) => { const score = item.terms.reduce((score, term) => score + (has(term) ? term.includes(" ") ? 4 : 2 : 0), 0); return { key, score: score + (key === "validation" && score > 0 ? 6 : 0) }; }).filter(item => item.score > 0).sort((a, b) => b.score - a.score);
  const followup = /^(and )?(more|more detail|explain more|tell me more|example|give me an example|show an example|how about that|why|what does that mean)$/.test(q);
  const remembered = context.topic && topics[context.topic] && (!context.view || topics[context.topic].view === context.view) ? context.topic : undefined;
  const topic = ranked[0]?.key ?? (followup ? remembered ?? (context.view && topics[context.view] ? context.view : undefined) : undefined);
  if (topic) return result(topic, /\bexample\b/.test(q) ? "example" : /\b(more|detail|rollback|roll back|release evidence|release decision)\b/.test(q) ? "detail" : "normal", context);
  if (followup && context.topic?.startsWith("screen:")) {
    const view = context.topic.slice(7);
    if (topics[view]) return result(view, /\bexample\b/.test(q) ? "example" : "detail", context);
    if (guides[view]) return { topic: context.topic, view, text: guides[view].steps.join(" "), suggestions: suggestedQuestions(view) };
  }
  if (/^(hi|hello|hey|thanks|thank you)$/.test(q)) return { topic: "welcome", text: "Hi! I can guide you through the app, explain treasury terms and troubleshoot common upload errors. Ask a question, choose a suggestion, or start the tour.", suggestions: ["Explain this screen", "How do I upload a CSV?", "How do I run a simulation?"] };
  return { topic: "unknown", text: "I couldn't match that to my built-in app guidance. Are you asking about uploading cash flows, a calculation, source data or go-live? Choose a suggestion or include the field name or error message. I cannot inspect your uploaded file or invent an answer.", suggestions: ["Explain this screen", "My file has an error", "Why is go-live blocked?"] };
}
