export type Guide = { title: string; steps: string[] };
export const guides: Record<string, Guide> = {
  overview: { title: "Start with your cash picture", steps: ["Read deployable cash, the cash buffer and the 13-week ending cash together.", "A dash means data is unavailable, not zero. Use Refresh workspace to retry.", "Check the data label: the public demo shows recorded synthetic results."] },
  forecast: { title: "Read the cash forecast", steps: ["Compare weekly closing cash with the minimum buffer.", "A shortfall means cash falls below the configured buffer; ending cash alone can hide earlier gaps.", "Weekly figures do not show every shortage within a day or week."] },
  energy: { title: "Explore the fictional oil business", steps: ["Choose Base, Receipt Delay, Cargo Cost Up, USD Funding Pressure or Combined to compare recorded scenarios.", "Look at maximum buffer shortfall and the first breach week.", "These are fictional UK and Singapore cash flows, not Shell company data or live oil prices."] },
  planning: { title: "Upload, check, then try a scenario", steps: ["Download the CSV example, or export your spreadsheet as UTF-8 CSV. Native XLSX and PDF are unsupported.", "Choose your file, map reference/date/amount, then Check data. Fix every error before using the preview.", "Choose Use checked data in simulator. Enter opening USD cash, buffer, dates and any manual FX rates.", "Change receipt delays, payments, oil-linked cash flows or FX, then Calculate comparison. Download the results after recalculating."] },
  risk: { title: "Understand risk reports", steps: ["Review FX hedges, derivative exposure, interest rates and counterparties.", "Read the warnings and data-source labels alongside the numbers.", "These reports support a human review; the guide cannot place trades or recommend a hedge."] },
  funding: { title: "Find where cash can move", steps: ["Review entity cash, funding concentration and mobility constraints.", "Group cash may be unavailable to another entity because of local restrictions.", "Transfers require the relevant treasury, legal and tax reviews."] },
  integrations: { title: "Check the quality of source data", steps: ["Review mapping, reconciliation, freshness and source authority.", "SHADOW means the source is being checked; ACTIVE requires the configured gates and human promotion.", "A working connector alone does not certify bank or ERP data."] },
  governance: { title: "Understand why go-live is blocked", steps: ["Read the controlled go-live gate and its missing evidence.", "Company sign-in and a configured backend are required for governed workflow actions; public demo writes are disabled.", "Independent validation, security, recovery, UAT and named human sign-offs remain required. Missing evidence cannot be assumed passed."] },
  agents: { title: "Meet the five reasoning teams", steps: ["The five teams cover liquidity, market risk, global treasury, governance and orchestration.", "Deterministic engines calculate the numbers; AI supports interpretation and humans approve actions.", "Live AI requires configured model access. Mint is a built-in app guide and does not call a model."] },
  analytics: { title: "Find a specialist analysis", steps: ["Search a topic such as liquidity, collateral or forecasts.", "Select an analysis to load its report.", "Check warnings and missing-data messages before using the output."] },
};
export const tour = [
  { view: "overview", title: "1. Get your bearings", text: "Start with cash, the minimum buffer and risk signals. Public demo numbers are fictional recorded results." },
  { view: "energy", title: "2. Learn with the energy example", text: "Select the Receipt Delay or Combined scenario. Notice how late customer receipts can create a temporary cash gap." },
  { view: "planning", title: "3. Bring a cash-flow file", text: "Download the CSV example. Choose a CSV/TSV, map its columns, check every row and inspect the preview before applying it." },
  { view: "planning", title: "4. Run your own what-if", text: "Enter opening cash, buffer and FX assumptions. Try a 10-day receipt delay, calculate, then compare shortfalls and download the CSV." },
  { view: "governance", title: "5. Check the boundaries", text: "Review the go-live blockers. Local planning does not authorize payments or replace evidence and independent sign-offs." },
  { view: "agents", title: "6. Understand the model", text: "Five AI teams support treasury decisions. Deterministic engines calculate; humans approve. You are ready to explore." },
];
export function answerHelp(question: string): { text: string; view?: string } {
  const q = question.trim().toLowerCase();
  if (/privacy|private|save|stored|reload|refresh|file.*(go|sent)/.test(q)) return { text: "Planning files stay in browser memory. Navigating workspaces keeps them for this session; reloading clears them. They do not update approved records, evidence or payments. Mint does not send your question to an AI service.", view: "planning" };
  if (/csv|xlsx|excel|upload|pdf|map|duplicate|column|file/.test(q)) return { text: guides.planning.steps.slice(0, 3).join(" "), view: "planning" };
  if (/delay|what.?if|simulat|scenario|oil|exchange|fx rate/.test(q)) return { text: "In Upload & what if, enter your opening USD cash, buffer, forecast dates and manual FX rates. Change the delay or percentage inputs and Calculate comparison. Oil changes affect crude-purchase and product-sale amounts, not hedge or inventory valuations. Recalculate after changes before downloading.", view: "planning" };
  if (/shortfall|headroom|buffer|forecast/.test(q)) return { text: "The buffer is the minimum cash target. Headroom is closing cash minus that buffer; negative headroom creates a shortfall. Compare every week, because a healthy final balance can hide an earlier gap. Weekly closing balances do not establish intraday solvency.", view: "forecast" };
  if (/live|real|approv|sign.?in|production|blocked|go.?live|certif/.test(q)) return { text: guides.governance.steps.join(" "), view: "governance" };
  if (/agent|gpt|model|ai|team/.test(q)) return { text: guides.agents.steps.join(" "), view: "agents" };
  if (/trade|hedge|invest|payment|transfer|buy|sell/.test(q)) return { text: "I explain app controls and reports. I cannot recommend or execute trades, payments or transfers. Use the risk reports and the governed human review process.", view: "risk" };
  return { text: "I have built-in help for this application. Try asking how to upload a CSV, run a what-if, read a cash buffer or understand go-live blockers. Use Explain this screen or Start tour for step-by-step help." };
}
