export type Guide = { title: string; steps: string[] };
export const guides: Record<string, Guide> = {
  company: { title: "Set up your company", steps: ["Register the company profile, then register legal entities for review. Saving requires an authenticated Group Treasurer.", "Pending registrations do not enter treasury calculations. Connect verified data and provision staff roles through your operator.", "Each company needs its own deployment and database. The public demo cannot save company records or clear production gates."] },
  start: { title: "Choose what you want to do", steps: ["Open Company setup to register your business and review entities and staff roles. The energy demo remains available under More reports.", "Start cash planning to choose data, check records, set assumptions, try a scenario and read the results.", "Review readiness to see missing evidence and human sign-offs before real execution."] },
  overview: { title: "Start with your cash picture", steps: ["Read deployable cash, the cash buffer and the 13-week ending cash together.", "A dash means data is unavailable, not zero. Use Refresh workspace to retry.", "Check the data label: the public demo shows recorded synthetic results."] },
  forecast: { title: "Read the cash forecast", steps: ["Compare weekly closing cash with the minimum buffer.", "A shortfall means cash falls below the configured buffer; ending cash alone can hide earlier gaps.", "Weekly figures do not show every shortage within a day or week."] },
  energy: { title: "Explore the fictional oil business", steps: ["Choose Base, Receipt Delay, Cargo Cost Up, USD Funding Pressure or Combined to compare recorded scenarios.", "Look at maximum buffer shortfall and the first breach week.", "These are fictional UK and Singapore cash flows, not Shell company data or live oil prices."] },
  planning: { title: "Upload, check, then try a scenario", steps: ["Download the CSV example, or export your spreadsheet as UTF-8 CSV. Native XLSX and PDF are unsupported.", "Choose your file, map reference/date/amount, then Check data. Fix every error before using the preview.", "Choose Use checked data in simulator. Enter opening USD cash, buffer, dates and any manual FX rates.", "Choose Continue to scenario. Change receipt delays, payments, oil-linked cash flows or FX, then Calculate comparison. Download the results after recalculating."] },
  risk: { title: "Understand risk reports", steps: ["Review FX hedges, derivative exposure, interest rates and counterparties.", "Read the warnings and data-source labels alongside the numbers.", "These reports support a human review; the guide cannot place trades or recommend a hedge."] },
  funding: { title: "Find where cash can move", steps: ["Review entity cash, funding concentration and mobility constraints.", "Group cash may be unavailable to another entity because of local restrictions.", "Transfers require the relevant treasury, legal and tax reviews."] },
  integrations: { title: "Check the quality of source data", steps: ["Review mapping, reconciliation, freshness and source authority.", "SHADOW means the source is being checked; ACTIVE requires the configured gates and human promotion.", "A working connector alone does not certify bank or ERP data."] },
  governance: { title: "Understand why go-live is blocked", steps: ["Read the controlled go-live gate and its missing evidence.", "Company sign-in and a configured backend are required for governed workflow actions; public demo writes are disabled.", "Independent validation, security, recovery, UAT and named human sign-offs remain required. Missing evidence cannot be assumed passed."] },
  agents: { title: "Meet the five reasoning teams", steps: ["The five teams cover liquidity, market risk, global treasury, governance and orchestration.", "Deterministic engines calculate the numbers; AI supports interpretation and humans approve actions.", "Live AI requires configured model access. Mint is a built-in app guide and does not call a model."] },
  analytics: { title: "Find a specialist analysis", steps: ["Search a topic such as liquidity, collateral or forecasts.", "Select an analysis to load its report.", "Check warnings and missing-data messages before using the output."] },
};
export const tour = [
  { view: "start", title: "1. Choose a task", text: "Set up your company, start cash planning, or review readiness. The menu keeps all specialist reports available." },
  { view: "company", title: "2. Set up your business", text: "Register your company profile and entities for review. Company sign-in and a hosted backend are required to save. Pending records do not activate treasury data." },
  { view: "planning", title: "3. Bring a cash-flow file", text: "Download the CSV example. Choose a CSV/TSV, map its columns, check every row and inspect the preview before applying it." },
  { view: "planning", title: "4. Run your own what-if", text: "Enter opening cash, buffer and FX assumptions. Try a 10-day receipt delay, calculate, then compare shortfalls and download the CSV." },
  { view: "governance", title: "5. Check the boundaries", text: "Review the go-live blockers. Local planning does not authorize payments or replace evidence and independent sign-offs." },
  { view: "agents", title: "6. Understand the model", text: "Five AI teams support treasury decisions. Deterministic engines calculate; humans approve. You are ready to explore." },
];
export type HelpContext = { view?: string; topic?: string; recordedDemo?: boolean };
export type HelpAnswer = { text: string; view?: string; topic: string; suggestions: string[] };
const topics: Record<string, { view: string; terms: string[]; text: string; detail: string; example: string; suggestions: string[] }> = {
  company: { view: "company", terms: ["company setup", "register company", "business setup", "onboarding", "legal entity", "staff roles"], text: guides.company.steps.join(" "), detail: "The authenticated Group Treasurer saves profile metadata and pending legal-entity registrations with an audit trail. Reporting currency is deployment configuration. Pending registrations do not enter treasury engines, grant roles or clear go-live gates.", example: "A manufacturing company can register its profile and an Indian subsidiary with INR functional currency. The operator must separately review entity configuration, currency support, bank mappings and evidence before live use.", suggestions: ["Explain this screen", "Why is go-live blocked?"] },
  upload: { view: "planning", terms: ["upload", "csv", "xlsx", "excel", "pdf", "columns", "mapping", "map", "spreadsheet", "file format"], text: "Export your sheet as UTF-8 CSV or TSV. Choose the file in Choose data, match reference, due date and amount columns in Check records, then Check data. Preview the rows before choosing Use checked data in simulator. Enter your opening cash, buffer and FX assumptions after applying the file.", detail: "Use unique references, valid YYYY-MM-DD dates and plain amounts with at most two decimals. Optional columns include direction, currency, entity, category and receipt probability. Limits are 500 records, 30 columns and 512 KB. Native Excel workbooks and PDFs are unsupported.", example: "Example CSV row: SALE-01,2026-10-10,1000,INFLOW,USD. Use headers id,date,amount,direction,currency. A negative signed amount without a direction is treated as an outflow.", suggestions: ["My file has an error", "How do I run a simulation?"] },
  validation: { view: "planning", terms: ["duplicate", "invalid", "validation", "file error", "upload error", "file has an error", "date error", "format error", "missing rate", "missing fx", "exchange rate error"], text: "Read the record number and error from Check data. Fix the original file and upload it again; one invalid record blocks application of the entire dataset. Duplicate references need unique IDs. Dates must be real YYYY-MM-DD dates, and amounts must have no commas or currency symbols.", detail: "For a missing exchange rate, enter Assumed USD per 1 currency under Set your starting position. Applying a file deliberately clears the fictional cash, buffer and FX assumptions. Crude purchases must be outflows, product sales inflows, and payments must have probability 1.", example: "A date such as 2026-02-30 is invalid. Two rows both called SALE-01 are duplicates. Use separate business references; do not delete legitimate transactions just to make the check pass.", suggestions: ["Show a CSV example", "What assumptions do I need?"] },
  assumptions: { view: "planning", terms: ["assumptions", "opening cash", "starting cash", "starting position", "manual rate", "fx rates", "exchange rates"], text: "Enter opening cash and the minimum buffer as USD equivalents, then choose the start date and 1–52 forecast weeks. For each non-USD currency, enter how many US dollars equal one unit of that currency. Rates are your manual assumptions, not live prices.", detail: "No credit facilities are included in this planner. FX shocks change future non-USD flows while opening USD cash stays fixed. Overdue and post-horizon flows are excluded and reported separately. Set every assumption before calculating.", example: "If one GBP is assumed to equal USD 1.25, enter 1.25 for GBP. This is an example rate, not a current market quote.", suggestions: ["How do I run a simulation?", "What is a cash buffer?"] },
  simulation: { view: "planning", terms: ["simulate", "simulation", "simulator", "what if", "what-if", "delay", "scenario", "oil", "shock", "recalculate"], text: "In Cash planning, set your starting position, choose Continue to scenario, adjust a receipt delay or percentage change, then Calculate comparison. Compare base and scenario cash week by week, especially maximum shortfall and the first buffer breach. Recalculate after editing inputs.", detail: "Receipt delays range from 0 to 90 days. Percentage changes range from -100% to +200% in 0.1% steps. Applicable changes multiply. Oil changes adjust crude-purchase and product-sale cash amounts; they do not value inventory or hedges. Weekly closing cash can hide intraday gaps.", example: "Try the fictional sample with a 10-day receipt delay and other shocks at zero: ending cash stays USD 34.2 million, but the scenario has a USD 2.8 million shortfall in week 2. This is a synthetic example, not a prediction for your company.", suggestions: ["What does shortfall mean?", "How do I download results?"] },
  buffer: { view: "forecast", terms: ["shortfall", "headroom", "buffer", "forecast", "cash gap", "negative cash", "liquidity"], text: "The cash buffer is the minimum cash target. In the private planner, headroom is weekly closing cash minus the buffer. Negative headroom becomes a shortfall. Check every week: a good ending balance can hide an earlier shortage.", detail: "The overview liquidity report may also include eligible facilities and other engine-specific adjustments; read its fields rather than assuming every report uses the planner formula. Weekly values do not establish intraday solvency or cash availability in each legal entity.", example: "Illustration: USD 12 million closing cash with a USD 15 million buffer gives minus USD 3 million headroom and a USD 3 million shortfall. This example uses the private planner's formula.", suggestions: ["How do I run a simulation?", "Explain this screen"] },
  privacy: { view: "planning", terms: ["privacy", "private", "stored", "save", "saved", "sent", "secure", "reload", "refresh", "remember", "memory"], text: "Planning files and this help conversation stay in browser memory. Moving between workspaces preserves them during the session; reloading clears them. Mint does not send questions or uploaded file contents to an AI service.", detail: "The planner does not write to approved forecasts, bank balances, release evidence or payments. Downloaded CSVs are files on your device and are not deleted by refreshing. Clear conversation removes Mint's session history without changing your planning dataset.", example: "If you reload the page after uploading a file, you will need to choose it again. If you download a comparison, that exported file remains on your device.", suggestions: ["How do I download results?", "Is this live company data?"] },
  export: { view: "planning", terms: ["download", "export", "comparison csv", "results file"], text: "After Calculate comparison, choose Download comparison to save weekly base/scenario closing cash, buffer and scenario shortfall as CSV. If you change inputs, the export is disabled until you calculate again.", detail: "Download CSV example gives you a fictional input template; Download comparison exports results. These are different files. Exports contain calculated values, not a certification or permission to execute payments.", example: "Change a receipt delay from 0 to 10 days, calculate again, then download. The CSV should match the newly displayed scenario.", suggestions: ["How do I upload a CSV?", "Where are my files stored?"] },
  governance: { view: "governance", terms: ["go live", "go-live", "production", "blocked", "approval", "approve", "certification", "certified", "sign in", "login", "real data", "live data", "company data", "bank connection"], text: guides.governance.steps.join(" "), detail: "A working website or connector does not clear production gates. Real bank/ERP feeds, independent model validation, security and recovery evidence, UAT and role-based human sign-offs remain separate requirements. Do not treat unavailable evidence as passed.", example: "A SHADOW source can be connected for validation while still being excluded from authoritative calculations. It needs its configured gates and human promotion before becoming ACTIVE.", suggestions: ["What does SHADOW mean?", "How do the AI teams work?"] },
  integrations: { view: "integrations", terms: ["shadow", "active", "reconciliation", "source", "connector", "erp", "integration"], text: guides.integrations.steps.join(" "), detail: "Compare completeness, timeliness, validity, uniqueness and reconciliation. A missing mapping or failed check should remain visible as quarantine or blocking evidence, rather than silently entering treasury calculations.", example: "An unmapped bank account needs a reviewed internal mapping before its records can be accepted. Source activation remains a human-controlled decision.", suggestions: ["Why is go-live blocked?", "Is this live company data?"] },
  agents: { view: "agents", terms: ["agent", "agents", "gpt", "model", "ai", "teams", "artificial intelligence"], text: guides.agents.steps.join(" "), detail: "The architecture preserves five GPT-6 Astra reasoning teams with token-efficient routing. This guide is separate from those teams. It uses curated rules and session context; there is no live GPT call or claim of model-generated analysis here.", example: "Use Mint to learn where a report is and how to read its fields. Use the treasury workflow for calculations, evidence review and human decisions.", suggestions: ["Explain this screen", "Why is go-live blocked?"] },
};
function result(topic: string, mode: "normal" | "detail" | "example" = "normal"): HelpAnswer {
  const item = topics[topic];
  return { topic, view: item.view, text: mode === "detail" ? item.detail : mode === "example" ? item.example : item.text, suggestions: item.suggestions };
}
export function answerHelp(question: string, context: HelpContext = {}): HelpAnswer {
  const q = question.trim().toLowerCase().replace(/[’']/g, "").replace(/[^a-z0-9-]+/g, " ").trim();
  const has = (phrase: string) => (` ${q} `).includes(` ${phrase} `);
  if (/\b(buy|sell|execute|place|send|approve|activate)\b/.test(q) && /\b(trade|hedge|payment|transfer|release|source)\b/.test(q)) return { topic: "boundary", view: "governance", text: "I can explain app controls and reports, but I cannot execute or approve trades, payments, transfers, releases or source activation. Those actions stay in the governed workflow with the required human roles and evidence.", suggestions: ["Why is go-live blocked?", "Explain this screen"] };
  if (["explain this screen", "this screen", "what can i do here", "what next", "what now", "where do i start"].some(has)) {
    const view = context.view && guides[context.view] ? context.view : "overview";
    return { topic: `screen:${view}`, view, text: `${guides[view].title}. ${guides[view].steps.join(" ")}`, suggestions: ["How do I upload a CSV?", "How do I run a simulation?"] };
  }
  if (/\b(live|real)\b/.test(q) && /\b(data|numbers|results|company)\b/.test(q)) return { topic: "governance", view: "governance", text: context.recordedDemo === false ? "This screen is connected to the configured backend. Check its source authority, timestamps and production gates; a backend connection does not prove all sources are real, fresh or approved. The private planner still uses your local assumptions." : "The public dashboard shows recorded synthetic results. The private planner calculates fresh results from the sample or your uploaded file, but has no live market feed. Mint does not have a live GPT connection.", suggestions: ["Why is go-live blocked?", "What assumptions do I need?"] };
  const ranked = Object.entries(topics).map(([key, item]) => { const score = item.terms.reduce((score, term) => score + (has(term) ? term.includes(" ") ? 4 : 2 : 0), 0); return { key, score: score + (key === "validation" && score > 0 ? 6 : 0) }; }).filter(item => item.score > 0).sort((a, b) => b.score - a.score);
  const followup = /^(and )?(more|more detail|explain more|tell me more|example|give me an example|show an example|how about that|why|what does that mean)$/.test(q);
  const topic = ranked[0]?.key ?? (followup && context.topic && topics[context.topic] ? context.topic : undefined);
  if (topic) return result(topic, /\bexample\b/.test(q) ? "example" : /\b(more|detail)\b/.test(q) ? "detail" : "normal");
  if (followup && context.topic?.startsWith("screen:")) {
    const view = context.topic.slice(7);
    if (guides[view]) return { topic: context.topic, view, text: guides[view].steps.join(" "), suggestions: ["How do I upload a CSV?", "What is a cash buffer?"] };
  }
  if (/^(hi|hello|hey|thanks|thank you)$/.test(q)) return { topic: "welcome", text: "Hi! I can guide you through the app, explain treasury terms and troubleshoot common upload errors. Ask a question, choose a suggestion, or start the tour.", suggestions: ["Explain this screen", "How do I upload a CSV?", "How do I run a simulation?"] };
  return { topic: "unknown", text: "I couldn't match that to my built-in app guidance. Are you asking about uploading cash flows, a calculation, source data or go-live? Choose a suggestion or include the field name or error message. I cannot inspect your uploaded file or invent an answer.", suggestions: ["Explain this screen", "My file has an error", "Why is go-live blocked?"] };
}
